### ISSUE TITLE
lookup("NEG PRP VB") only returns one sentence

### ISSUE THREAD

**Issue by davidmoeljadi** [neocl/itctk#4]
lookup("NEG PRP VB") cannot find:
"belum/NEG kita/PRP lakukan/VB"
it can only find:
Bukan/NEG -nya/PRP menceburkan/VB

**Comment by letuananh** [comment]
I used re.match() instead of re.search(). It's fixed now.
Ref: https://docs.python.org/3/library/re.html#search-vs-match
